spring.application.name=postgre

# Conexao com o RDS PostgreSQL - valores injetados via variaveis de ambiente no container
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${SERVER_PORT:8080}

aws.sns.topic-arn=arn:aws:sns:us-east-2:235851854474:topic-sns-aws
aws.sqs.queue-url=https://sqs.us-east-2.amazonaws.com/235851854474/fila-cep-sns
aws.region=us-east-2