spring.application.name=postgre

# Conexao com o RDS PostgreSQL
spring.datasource.url=jdbc:postgresql://rds-postgre.cx6oi0yq8vx4.us-east-2.rds.amazonaws.com:5432/postgre
spring.datasource.username=postgres
spring.datasource.password=gabs1234
spring.datasource.driver-class-name=org.postgresql.Driver